SUPABASE_URL = "https://jfxhgqxrbjnfnrhqwuap.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpmeGhncXhyYmpuZm5yaHF3dWFwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjYzNDY4NDUsImV4cCI6MjA4MTkyMjg0NX0.SQ2Y_m6LLuvtkwF31NJJsFxmF0bCt0-m6fhivHwiLBY"
